name: 'Should I notify slack?'
description: 'Decide if a notification to slack is necessary taking into account the previous build result.'
branding:
  icon: 'bell'
  color: 'green'
inputs:
  needs_context:
    description: 'json representation of the `needs` object in your context (`toJson(needs)`)'
    required: true
  branch:
    description: 'The branch to get the status from'
    required: true
    default: 'main'
  github_token:
    description: 'A github token (secrets.GITHUB_TOKEN will suffice)'
    required: true
  notify_on_changed_status:
    description: 'Set to a non-empty string to return yes if and only if the status changed'
    required: false
    default: ''
outputs:
  should_send_message:
    description: "`yes|no` depending on if the message should be sent"
    value: ${{ steps.determine-notification.outputs.should_send_message }}
  last_status:
    description: "status of the last completed workflow"
    value: ${{ steps.determine-notification.outputs.last_status }}
runs:
  using: "composite"
  steps:
    - name: Determine if we need to notify
      id: determine-notification
      shell: bash
      run: |
        workflow_id=$(curl --header 'authorization: Bearer ${{ inputs.github_token }}' \
            --header 'content-type: application/json' \
            https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }} | jq -r .workflow_id)
        echo "workflow id: $workflow_id"
        last_status=$(curl --silent --header 'authorization: Bearer ${{ inputs.github_token }}' \
                      --header 'content-type: application/json' \
                      "https://api.github.com/repos/${{ github.repository }}/actions/workflows/$workflow_id/runs?per_page=1&status=completed&branch=${{ inputs.branch }}" | jq -r .workflow_runs[0].conclusion)
        if [[  $last_status != success && $last_status != failure && $last_status != null ]]; then
            echo "Invalid \$last_status: $last_status"
            exit 1
        else
            echo "status of the previous build: $last_status"
            echo "::set-output name=last_status::$last_status"
        fi
        needs_context="${{ inputs.needs_context }}"
        if [[ $(echo $needs_context | grep "result: failure") ]]; then
            current_status=failure
        else
            current_status=success
        fi
        if [[ "${{ inputs.notify_on_changed_status }}" ]]; then
            if [[ $current_status == $last_status ]]; then
              echo "::set-output name=should_send_message::no"
            else
              echo "::set-output name=should_send_message::yes"
            fi
        else
          if [[ $current_status == failure ]]; then
            echo "::set-output name=should_send_message::yes"
          elif [[ $last_status == failure ]]; then
            echo "::set-output name=should_send_message::yes"
          else
            echo "::set-output name=should_send_message::no"
          fi
        fi
